/*
  This test demonstrates resources are not generated by pools.
*/

source tick
auto pool count
tick --> count
assert ends : count < 100 "ok"

auto pull pool A at 1
auto pull pool B
A --> B
B --> A

assert sane : A + B == 1
  "resources are not generated or consumed when they flow between pulling pools"

assert sane : (A == 1 && B == 0) || (A == 0 && B == 1)
  "resources should flow when pulled"
